from __future__ import annotations

from copy import deepcopy
from typing import Any

TRACKER_VERSION = "project_finish_tracker_v2"

_TRACKER_ITEMS: tuple[dict[str, Any], ...] = (
    {
        "id": "post_implementation_verification",
        "area": "verification",
        "title": "Post-Implementation Verification",
        "status": "in_progress",
        "priority": "critical",
        "why_it_matters": "The new proof-first docs make verification the first active step before deeper evidence or expansion work.",
        "remaining_work": [
            "Keep backend, frontend, report, route, and safety-boundary checks current after each proof-layer change.",
            "Record proof gaps honestly in the verification report instead of treating green health checks as proof.",
            "Confirm no analytics, AI, broker, or UI surface changed order authority, route authority, risk gates, or ranking weights.",
        ],
        "done_when": "The verification report is current, cites focused test/build/browser evidence, and lists remaining proof blockers without overclaiming readiness.",
        "safe_boundary": "Verification only; does not change runtime trading behavior.",
    },
    {
        "id": "data_completeness_hardening",
        "area": "evidence_quality",
        "title": "Data completeness hardening",
        "status": "in_progress",
        "priority": "critical",
        "why_it_matters": "No benchmark, reward, forecast, or walk-forward claim is trustworthy while required proof fields are missing.",
        "remaining_work": [
            "Raise coverage for forward returns, baseline returns, forecast actual paths, cost fields, regimes, and reward fields.",
            "Keep missing-field counts visible by source and by proof gate.",
            "Prevent simulation evidence from being counted as real-time market-observed proof.",
        ],
        "done_when": "Data Completeness reports benchmark_ready and proof_field_ready with traceable source coverage.",
        "safe_boundary": "Diagnostics only; does not infer or fabricate missing evidence.",
    },
    {
        "id": "candidate_outcome_baseline_stamping",
        "area": "evidence_capture",
        "title": "Candidate outcome and baseline stamping",
        "status": "in_progress",
        "priority": "critical",
        "why_it_matters": "Professional Benchmark, Evidence Reward, Data Completeness, Score Calibration, and Walk-Forward all need rewardable candidate rows.",
        "remaining_work": [
            "Capture price_at_signal for every candidate before movement is measured.",
            "Attach closed-horizon observed prices for 5m, 15m, 30m, and declared horizons.",
            "Attach matched SPY, QQQ, sector, random-peer, momentum, mean-reversion, VWAP, ORB, and previous-close baselines.",
            "Capture spread, expected cost, paper fill, slippage, fill delay, and route evidence when available.",
        ],
        "done_when": "Rewardable candidate outcomes exist with actual_forward_return, baseline_forward_return, cost fields, and append-only lineage.",
        "safe_boundary": "Research evidence only; does not place orders, change routes, or change ranking weights automatically.",
    },
    {
        "id": "professional_benchmark_proof",
        "area": "benchmarking",
        "title": "Professional Benchmark proof gate",
        "status": "blocked_by_evidence",
        "priority": "critical",
        "why_it_matters": "This is the bridge between raw evidence and any cautious edge claim.",
        "remaining_work": [
            "Collect enough rewardable candidate outcomes for minimum sample size.",
            "Verify baseline-relative edge, score-bucket lift, and after-cost reward.",
            "Keep data-quality failure states explicit when proof is not ready.",
        ],
        "done_when": "Professional Benchmark reaches ready_for_human_review without claiming proven alpha.",
        "safe_boundary": "Human-review analytics only; no execution, route, risk, or ranking mutation.",
    },
    {
        "id": "walk_forward_validation",
        "area": "repeatability",
        "title": "Walk-forward validation",
        "status": "blocked_by_evidence",
        "priority": "high",
        "why_it_matters": "Repeatability claims need frozen parameters and out-of-sample evaluation.",
        "remaining_work": [
            "Create frozen experiment records with feature, strategy, reward, and baseline versions.",
            "Evaluate frozen windows against stamped candidate outcomes.",
            "Require after-cost support before any promotion review.",
        ],
        "done_when": "Walk-Forward shows frozen, no-lookahead, evaluated records with acceptable pass rate.",
        "safe_boundary": "Research registry only; does not update execution or ranking configuration.",
    },
    {
        "id": "score_calibration_feature_attribution",
        "area": "ranking_quality",
        "title": "Score calibration and feature attribution",
        "status": "blocked_by_evidence",
        "priority": "high",
        "why_it_matters": "Scores and features must separate good outcomes from bad outcomes before ranking quality claims are credible.",
        "remaining_work": [
            "Measure score-bucket lift on rewardable candidate outcomes.",
            "Add after-cost bucket lift and monotonicity checks.",
            "Track positive and negative feature drivers with manual review only.",
        ],
        "done_when": "Calibration proof is ready with sufficient feature coverage and after-cost lift.",
        "safe_boundary": "Does not change ranking weights automatically.",
    },
    {
        "id": "execution_quality_tca",
        "area": "execution_quality",
        "title": "Execution Quality and TCA",
        "status": "in_progress",
        "priority": "high",
        "why_it_matters": "Apparent edge is not usable unless it survives paper-route spread, slippage, latency, and fill quality.",
        "remaining_work": [
            "Link paper fills back to candidate lifecycle IDs.",
            "Improve cost evidence coverage and execution-adjusted outcome coverage.",
            "Track missed fills, partial fills, quote freshness, and alpha decay by setup and engine.",
        ],
        "done_when": "Execution proof is ready with candidate-route linkage and positive after-cost evidence.",
        "safe_boundary": "Paper analytics only; does not change broker routes or submit orders.",
    },
    {
        "id": "risk_gate_audit_trail_hardening",
        "area": "risk_and_audit",
        "title": "Risk Gate and Audit Trail hardening",
        "status": "in_progress",
        "priority": "critical",
        "why_it_matters": "The proof-first plan requires risk gates and audit history to stay authoritative before any stronger claim or expansion layer.",
        "remaining_work": [
            "Verify risk gates, kill switches, broker-route boundaries, and audit records are visible in the safety review.",
            "Tie risk and audit evidence to candidate, forecast, benchmark, execution, and promotion records where available.",
            "Keep support exports sanitized and free of secrets, broker records, raw logs, account IDs, raw paths, and credentials.",
        ],
        "done_when": "Risk and audit evidence is traceable, sanitized, and confirms no proof layer can bypass controls.",
        "safe_boundary": "Audit and verification only; does not loosen or enforce new risk settings.",
    },
    {
        "id": "portfolio_risk_intelligence",
        "area": "risk_visibility",
        "title": "Portfolio Risk Intelligence",
        "status": "in_progress",
        "priority": "high",
        "why_it_matters": "Edge has to be reviewed with exposure, concentration, factor, liquidity, drawdown, and stress context.",
        "remaining_work": [
            "Attach candidate and strategy context to exposure records.",
            "Improve factor, liquidity, stress, drawdown, and open-heat coverage.",
            "Keep portfolio risk recommendations visible as review items only.",
        ],
        "done_when": "Portfolio risk proof is ready with enough exposure and context coverage for review.",
        "safe_boundary": "Visibility only; does not enforce, loosen, or change risk gates.",
    },
    {
        "id": "human_system_shadow_mode",
        "area": "decision_review",
        "title": "Human vs System Shadow Mode",
        "status": "blocked_by_evidence",
        "priority": "medium",
        "why_it_matters": "Human override quality and system decision quality need same-opportunity comparisons with outcomes.",
        "remaining_work": [
            "Capture human thesis contracts before outcomes.",
            "Link human and system decisions to the same candidate opportunity.",
            "Attach outcome, cost, and risk context for fair comparison.",
        ],
        "done_when": "Shadow Mode has same-opportunity comparisons with pre-outcome human and system contracts.",
        "safe_boundary": "Comparison metadata only; does not place or block trades.",
    },
    {
        "id": "research_promotion_rules",
        "area": "promotion_governance",
        "title": "Research promotion rules",
        "status": "blocked_by_evidence",
        "priority": "high",
        "why_it_matters": "Nothing should move from research to operational policy without traceable benchmark, data, walk-forward, execution, and manual-review proof.",
        "remaining_work": [
            "Require traceability to benchmark, data-completeness, walk-forward, execution, and manual-review records.",
            "Keep promotion records as metadata until human approval.",
            "Block promotion when proof gates are missing or stale.",
        ],
        "done_when": "Promotion proof is ready with traceability coverage and no authority crossing.",
        "safe_boundary": "Research metadata only; does not write execution, broker, risk, or ranking config.",
    },
    {
        "id": "evidence_reward_and_blocker_value",
        "area": "reward_quality",
        "title": "Evidence Reward and blocker value",
        "status": "blocked_by_evidence",
        "priority": "high",
        "why_it_matters": "Reward and blocker claims are only useful when outcomes, baselines, costs, and blocked-move records are complete enough to measure.",
        "remaining_work": [
            "Increase rewardable prediction and blocked-move coverage with actual outcomes and baselines.",
            "Separate simulation evidence from real-time market-observed evidence.",
            "Report blocker value as insufficient evidence when required outcome fields are missing.",
        ],
        "done_when": "Evidence Reward can explain rewardability, blocker value, and after-cost outcomes without fabricated data or ranking mutation.",
        "safe_boundary": "Research-only reward analytics; does not change ranking weights automatically.",
    },
    {
        "id": "forecast_validation",
        "area": "forecast_quality",
        "title": "Forecast validation hardening",
        "status": "in_progress",
        "priority": "medium",
        "why_it_matters": "Forecast claims require timestamped contracts, actual paths, target/invalidation checks, and calibration evidence.",
        "remaining_work": [
            "Attach actual post-prediction paths broadly, not only fixtures.",
            "Preserve immutable forecast contracts separately from validation outcomes.",
            "Feed forecast quality into benchmark and data completeness without changing execution.",
        ],
        "done_when": "Forecast Validation stays ready with broad actual-path coverage and stable reward calculations.",
        "safe_boundary": "Read-only validation; does not alter execution, risk gates, or ranking weights.",
    },
    {
        "id": "proof_metrics_dashboard",
        "area": "proof_visibility",
        "title": "Proof metrics dashboard planning",
        "status": "in_progress",
        "priority": "medium",
        "why_it_matters": "The revised docs call for proof metrics before another major product layer moves into active work.",
        "remaining_work": [
            "Summarize data completeness, rewardability, benchmarkable candidates, forecast contract completeness, and baseline coverage.",
            "Add execution-cost coverage, frozen walk-forward count, score-bucket separation, shadow-mode matched records, and risk/audit coverage.",
            "Keep metrics as proof visibility, not readiness or alpha claims.",
        ],
        "done_when": "A shared proof-metrics view shows the current proof gaps and which gate each gap blocks.",
        "safe_boundary": "Read-only planning and reporting only.",
    },
    {
        "id": "proof_first_backlog_scoring",
        "area": "roadmap_discipline",
        "title": "Proof-first backlog scoring and expansion gates",
        "status": "in_progress",
        "priority": "high",
        "why_it_matters": "New desks, agents, brokers, provider spend, C++ work, and HFT research must stay deferred unless they improve proof and pass safety/data/benchmark/walk-forward/justification gates.",
        "remaining_work": [
            "Score future features on evidence, benchmark, walk-forward, execution quality, risk, auditability, trust, complexity, dependency risk, safety risk, and maintenance burden.",
            "Record Safety Gate, Data Gate, Benchmark Gate, Walk-Forward Gate, and Expansion Justification Gate answers before moving expansion work into active scope.",
            "Keep expansion items visible as future backlog when proof impact is low, unknown, or unsafe.",
        ],
        "done_when": "Every future feature has a proof-first decision of near-term, foundation-first, future backlog, or reject for now.",
        "safe_boundary": "Roadmap governance only; does not implement expansion features.",
    },
    {
        "id": "technical_analysis_evidence_setup_admission",
        "area": "setup_research",
        "title": "Technical Analysis evidence setup admission",
        "status": "in_progress",
        "priority": "high",
        "why_it_matters": "The updated technical-analysis research narrows setup work to objective, benchmarkable, execution-realistic methods instead of broad chart-lore expansion.",
        "remaining_work": [
            "Document high-priority setup families as evidence-only candidates: momentum/trend, volume, support/resistance, dynamic support/resistance, breakouts, reversals, market structure, and BOS.",
            "Keep oscillators, divergence, candlesticks, Fibonacci, trend lines, FVG, orderblocks, and CHoCH research-only or confirmation-only until they beat simpler controls.",
            "Keep Heikin Ashi, Renko, Elliott Wave, Gann, moon cycles, and weak harmonic variants out of setup admission unless future out-of-sample evidence clears the avoid gates.",
            "Require causal rules, executable pricing, matched baselines, walk-forward robustness, cost survival, parameter stability, and provenance before any method enters docs as an evidence setup.",
        ],
        "done_when": "Technical-analysis methods are classified into evidence-only, research-only, and avoid groups with method-specific fields, controls, and proof gates documented before implementation.",
        "safe_boundary": "Docs and research backlog only; does not add detectors, place orders, change ranking weights, or loosen risk gates.",
    },
    {
        "id": "ai_committee_research_layer",
        "area": "ai_research",
        "title": "AI Committee research layer",
        "status": "in_progress",
        "priority": "medium",
        "why_it_matters": "AI review is useful only when dissent, evidence quality, and safety boundaries are visible.",
        "remaining_work": [
            "Keep memos sanitized and append-only.",
            "Tie committee conclusions to benchmark, walk-forward, calibration, forecast, execution, and data-completeness statuses.",
            "Keep malformed or unsafe LLM output on deterministic fallback.",
        ],
        "done_when": "Committee reports add research context without approving trades or mutating live behavior.",
        "safe_boundary": "No AI order authority, no broker-route mutation, no risk-gate mutation, no ranking mutation.",
    },
    {
        "id": "operator_experience_docs",
        "area": "product_readiness",
        "title": "Operator experience, docs, and report UX",
        "status": "in_progress",
        "priority": "medium",
        "why_it_matters": "The app needs clear proof gates, safe next actions, and empty states before it is reliable for a serious user.",
        "remaining_work": [
            "Show this project finish tracker at the end of report surfaces.",
            "Keep docs aligned with live statuses and proof boundaries.",
            "Add customer-safe empty states and concise next safe actions for each report.",
            "Keep browser smoke checks and static frontend checks in the verification loop.",
        ],
        "done_when": "Every major report ends with the shared finish tracker and clear next safe actions.",
        "safe_boundary": "Documentation and UX only; does not loosen trading controls.",
    },
    {
        "id": "paper_to_live_gate",
        "area": "live_trading_boundary",
        "title": "Paper-to-live proof gate",
        "status": "not_started",
        "priority": "critical",
        "why_it_matters": "Live trading should stay blocked until paper evidence proves repeatability, data quality, costs, risk controls, and manual review.",
        "remaining_work": [
            "Pass Professional Benchmark, Walk-Forward, Data Completeness, Execution Quality, Portfolio Risk, and Shadow Mode proof gates.",
            "Complete operator runbooks, incident flow, kill-switch checks, reconciliation, and rollback evidence.",
            "Require explicit human review before any live-setting change.",
        ],
        "done_when": "Live enablement remains explicitly gated by verified paper evidence and human approval.",
        "safe_boundary": "No current tracker item authorizes live trading.",
    },
    {
        "id": "future_market_specialist_desks",
        "area": "future_backlog",
        "title": "Market Specialist Desk registry",
        "status": "deferred",
        "priority": "future",
        "why_it_matters": "Market context may help later, but more desks do not raise readiness without stronger proof.",
        "remaining_work": [
            "Keep Crypto, Precious Metals, Rates, FX, Energy, Index, Sector Rotation, Volatility, and Off-Exchange desks as context engines only.",
            "Require proof-first scoring and expansion gates before implementation.",
        ],
        "done_when": "Deferred until foundation proof is stronger and the smallest safe context-only version is justified.",
        "safe_boundary": "Future context only; not an order bot and not a trade trigger.",
    },
    {
        "id": "future_candidate_fusion_market_strategy_benchmark",
        "area": "future_backlog",
        "title": "Candidate Fusion and Market x Strategy Benchmark",
        "status": "deferred",
        "priority": "future",
        "why_it_matters": "Combining market context with strategy logic should happen only after current candidate, benchmark, and walk-forward evidence is trustworthy.",
        "remaining_work": [
            "Define market context, strategy logic, benchmark verdicts, and risk-gate authority as separate contracts.",
            "Prove current benchmark and walk-forward quality before adding market x strategy measurements.",
        ],
        "done_when": "Deferred until current benchmark, walk-forward, and candidate evidence can support market x strategy comparisons.",
        "safe_boundary": "Future research only; risk gates remain authoritative.",
    },
    {
        "id": "future_off_exchange_liquidity_research",
        "area": "future_backlog",
        "title": "Off-Exchange Liquidity Dashboard",
        "status": "deferred",
        "priority": "future",
        "why_it_matters": "Dark-liquidity context can be useful, but it must not be framed as hidden-order detection or a directional trading signal.",
        "remaining_work": [
            "Use free or delayed public research data where available.",
            "Measure whether off-exchange regimes improve candidate, execution, benchmark, or reward evidence.",
            "Avoid claims that prints predict direction, reveal hidden orders, or prove institutional intent.",
        ],
        "done_when": "Deferred until it solves a measured proof problem without changing ranking, routing, or order behavior.",
        "safe_boundary": "Passive research context only; not a trade trigger.",
    },
    {
        "id": "future_broker_neutral_provider_strategy",
        "area": "future_backlog",
        "title": "Broker-neutral architecture and provider ROI gates",
        "status": "deferred",
        "priority": "future",
        "why_it_matters": "Broker and provider expansion adds risk and cost unless current evidence proves a specific bottleneck.",
        "remaining_work": [
            "Keep Alpaca paper as the unattended execution lane until a separate approved project changes it.",
            "Define BrokerAdapter, MarketDataAdapter, capability registry, simulator adapter, ETF proxies, and route eligibility only after proof gates justify them.",
            "Use 3x expected monthly value over monthly cost as the minimum provider-pay threshold, with 5x preferred.",
        ],
        "done_when": "Deferred until data, benchmark, execution, or walk-forward evidence proves a broker/provider bottleneck and ROI case.",
        "safe_boundary": "No broker-route change, live execution, or provider spend is authorized.",
    },
    {
        "id": "future_visual_strategy_evidence_builder",
        "area": "future_backlog",
        "title": "Visual Strategy Evidence Builder",
        "status": "deferred",
        "priority": "future",
        "why_it_matters": "A visual builder should create evidence contracts, not encourage blind no-code trading before proof exists.",
        "remaining_work": [
            "Define visual rule contracts for replay, blocker, outcome, forecast, execution, reward, baseline, and walk-forward evidence.",
            "Prevent visual signals from auto-trading or bypassing proof gates.",
        ],
        "done_when": "Deferred until current evidence contracts are mature enough to make a visual builder proof-focused instead of feature-count-focused.",
        "safe_boundary": "Future evidence-contract UX only; not a no-code trading bot.",
    },
    {
        "id": "future_governance_institutional_controls",
        "area": "future_backlog",
        "title": "Governance, RBAC, model registry, and institutional controls",
        "status": "deferred",
        "priority": "future",
        "why_it_matters": "Firm-facing claims need real lineage, permissions, approvals, incident handling, and external review evidence.",
        "remaining_work": [
            "Add governance, RBAC, strategy registry, model registry, approval workflows, environment separation, and firm-grade sanitized reporting after foundation proof improves.",
            "Keep institutional-grade and compliance-approved language blocked until proof and reviews support it.",
        ],
        "done_when": "Deferred until the proof chain supports firm-facing control work and the required reviews are scoped.",
        "safe_boundary": "Future control-plane work only; does not create compliance approval.",
    },
    {
        "id": "future_cpp_hft_feasibility",
        "area": "future_backlog",
        "title": "C++ Core Accelerators and HFT feasibility study",
        "status": "deferred",
        "priority": "future",
        "why_it_matters": "Performance acceleration and HFT research should follow profiling and a separate infrastructure thesis, not roadmap ambition.",
        "remaining_work": [
            "Profile Python bottlenecks before adding C++ and keep C++ away from trading authority.",
            "Treat DMA, exchange connectivity, colocation, low-latency data, order book reconstruction, and HFT controls as a separate future thesis.",
        ],
        "done_when": "Deferred until profiling proves a research-only acceleration bottleneck or a separate HFT thesis is approved.",
        "safe_boundary": "Future research infrastructure only; no trading authority moves to C++ and no HFT claim is allowed.",
    },
)


def build_project_finish_tracker(*, report_name: str | None = None) -> dict[str, Any]:
    items = [deepcopy(item) for item in _TRACKER_ITEMS]
    status_counts: dict[str, int] = {}
    priority_counts: dict[str, int] = {}
    for item in items:
        status_counts[item["status"]] = status_counts.get(item["status"], 0) + 1
        priority_counts[item["priority"]] = priority_counts.get(item["priority"], 0) + 1
    return {
        "version": TRACKER_VERSION,
        "report_name": report_name or "project_report",
        "scope": "project_wide",
        "summary": {
            "total_items": len(items),
            "status_counts": status_counts,
            "priority_counts": priority_counts,
            "critical_open_items": sum(1 for item in items if item["priority"] == "critical" and item["status"] != "done"),
            "safe_boundary": "Tracker items are verification, proof, review, documentation, paper-operation, or deferred roadmap work only. They do not authorize live trading or expansion implementation.",
            "proof_first_rule": "Ambition is allowed. Proof decides priority.",
        },
        "items": items,
        "source_docs": [
            "docs/PROOF_FIRST_ROADMAP_DISCIPLINE.md",
            "docs/TEN_OUT_OF_TEN_30_60_90_DAY_PLAN.md",
            "docs/TEN_OUT_OF_TEN_ROADMAP.md",
            "docs/TEN_OUT_OF_TEN_CATEGORY_UPGRADE_MASTER_PLAN.md",
            "docs/TEN_OUT_OF_TEN_PROOF_GATES.md",
            "docs/CATEGORY_READINESS_RATINGS.md",
            "docs/TECHNICAL_ANALYSIS_EVIDENCE_SETUP_RESEARCH.md",
            "docs/PROOF_METRICS_DASHBOARD.md",
            "docs/BENCHMARK_TRIAGE_REPORT.md",
            "docs/RISK_GATE_AUDIT_TRAIL_HARDENING.md",
            "docs/POST_IMPLEMENTATION_VERIFICATION_REPORT.md",
        ],
    }
