from __future__ import annotations

import unittest

from backend.api import create_app
from backend.core.config import settings


class ApiRouteHealthTests(unittest.TestCase):
    def test_core_trading_routes_are_mounted_under_api_prefix(self) -> None:
        app = create_app()
        paths = {getattr(route, "path", "") for route in app.routes}
        prefix = settings.api_prefix.rstrip("/")

        expected_paths = {
            f"{prefix}/healthz",
            f"{prefix}/readyz",
            f"{prefix}/orgs/trade-automation",
            f"{prefix}/orgs/trade-automation/safety-state",
            f"{prefix}/orgs/trade-automation/daily-ledger",
            f"{prefix}/orgs/trade-automation/daily-safety-summary",
            f"{prefix}/orgs/trade-automation/hft-watchdog/latest",
            f"{prefix}/orgs/trade-automation/alpaca-paper-readiness",
            f"{prefix}/orgs/trade-automation/market-session",
            f"{prefix}/orgs/trade-automation/evidence-edge/summary",
            f"{prefix}/orgs/trade-automation/evidence-edge/blockers",
            f"{prefix}/orgs/trade-automation/evidence-edge/setups",
            f"{prefix}/orgs/trade-automation/evidence-edge/engines",
            f"{prefix}/orgs/trade-automation/evidence-edge/recommendations",
            f"{prefix}/orgs/trade-automation/evidence-reward/summary",
            f"{prefix}/orgs/trade-automation/evidence-reward/candidates",
            f"{prefix}/orgs/trade-automation/evidence-reward/blockers",
            f"{prefix}/orgs/trade-automation/evidence-reward/engines",
            f"{prefix}/orgs/trade-automation/evidence-reward/setups",
            f"{prefix}/orgs/trade-automation/evidence-reward/ai",
            f"{prefix}/orgs/trade-automation/evidence-reward/regimes",
            f"{prefix}/orgs/trade-automation/no-trade-report",
            f"{prefix}/orgs/trade-automation/market-day-report",
            f"{prefix}/orgs/trade-automation/position-promotion",
            f"{prefix}/orgs/trade-automation/desks",
            f"{prefix}/orgs/trade-automation/desks/{{desk_key}}/export",
            f"{prefix}/orgs/trade-automation/desks/{{desk_key}}/reset",
            f"{prefix}/live/status",
            f"{prefix}/live/orders",
            f"{prefix}/strategies",
            f"{prefix}/readiness/desk",
            f"{prefix}/readiness/category-upgrade",
            f"{prefix}/readiness/category-upgrade/proof-gates",
            f"{prefix}/readiness/category-upgrade/proof-chain",
            f"{prefix}/readiness/category-upgrade/backlog",
            f"{prefix}/readiness/category-upgrade/support-export",
            f"{prefix}/risk/policies",
            f"{prefix}/portfolio-risk/summary",
            f"{prefix}/portfolio-risk/exposures",
            f"{prefix}/portfolio-risk/concentration",
            f"{prefix}/portfolio-risk/correlation",
            f"{prefix}/portfolio-risk/stress-tests",
            f"{prefix}/portfolio-risk/regimes",
            f"{prefix}/audit/events",
            f"{prefix}/ai-agents/summary",
            f"{prefix}/ai-agents/roles",
            f"{prefix}/ai-agents/memos",
            f"{prefix}/ai-agents/memos/{{memo_id}}",
            f"{prefix}/ai-agents/committee/latest",
            f"{prefix}/ai-agents/safety",
            f"{prefix}/ai-agents/llm-status",
            f"{prefix}/ai-agents/readiness-backlog",
            f"{prefix}/ai-agents/external-review",
            f"{prefix}/ai-agents/proposals",
            f"{prefix}/ai-agents/proposals/{{proposal_id}}/decision",
            f"{prefix}/ai-agents/run-role/{{role_name}}",
            f"{prefix}/ai-agents/run-committee",
            f"{prefix}/ai-agents/run-desk/{{desk_name}}",
            f"{prefix}/execution-analytics/summary",
            f"{prefix}/execution-quality/summary",
            f"{prefix}/execution-quality/trades",
            f"{prefix}/execution-quality/slippage",
            f"{prefix}/execution-quality/alpha-decay",
            f"{prefix}/execution-quality/engines",
            f"{prefix}/execution-quality/setups",
            f"{prefix}/evidence-edge/summary",
            f"{prefix}/evidence-edge/blockers",
            f"{prefix}/evidence-edge/setups",
            f"{prefix}/evidence-edge/engines",
            f"{prefix}/evidence-edge/recommendations",
            f"{prefix}/evidence-reward/summary",
            f"{prefix}/evidence-reward/candidates",
            f"{prefix}/evidence-reward/blockers",
            f"{prefix}/evidence-reward/engines",
            f"{prefix}/evidence-reward/setups",
            f"{prefix}/evidence-reward/ai",
            f"{prefix}/evidence-reward/regimes",
            f"{prefix}/forecast-validation/summary",
            f"{prefix}/forecast-validation/predictions",
            f"{prefix}/forecast-validation/models",
            f"{prefix}/forecast-validation/regimes",
            f"{prefix}/professional-benchmark/summary",
            f"{prefix}/professional-benchmark/baselines",
            f"{prefix}/professional-benchmark/score-buckets",
            f"{prefix}/professional-benchmark/blockers",
            f"{prefix}/professional-benchmark/ai",
            f"{prefix}/professional-benchmark/forecast",
            f"{prefix}/professional-benchmark/execution",
            f"{prefix}/data-completeness/summary",
            f"{prefix}/data-completeness/candidates",
            f"{prefix}/data-completeness/forecasts",
            f"{prefix}/data-completeness/ai",
            f"{prefix}/data-completeness/blockers",
            f"{prefix}/data-completeness/execution",
            f"{prefix}/data-completeness/benchmark-readiness",
            f"{prefix}/walk-forward/summary",
            f"{prefix}/walk-forward/experiments",
            f"{prefix}/walk-forward/experiments/{{experiment_id}}",
            f"{prefix}/walk-forward/experiments",
            f"{prefix}/walk-forward/experiments/{{experiment_id}}/freeze",
            f"{prefix}/walk-forward/experiments/{{experiment_id}}/clone",
            f"{prefix}/research-promotion/summary",
            f"{prefix}/research-promotion/entities",
            f"{prefix}/research-promotion/entities/{{entity_id}}",
            f"{prefix}/research-promotion/entities/{{entity_id}}/status",
            f"{prefix}/score-calibration/summary",
            f"{prefix}/score-calibration/buckets",
            f"{prefix}/score-calibration/features",
            f"{prefix}/score-calibration/regimes",
            f"{prefix}/score-calibration/recommendations",
            f"{prefix}/shadow-mode/summary",
            f"{prefix}/shadow-mode/records",
            f"{prefix}/shadow-mode/comparisons",
            f"{prefix}/shadow-mode/bias",
            f"{prefix}/shadow-mode/human-thesis",
        }

        missing = sorted(path for path in expected_paths if path not in paths)
        self.assertEqual(missing, [])


if __name__ == "__main__":
    unittest.main()
