from __future__ import annotations
from datetime import datetime
from typing import Protocol, Sequence
from institutional_trading.models import DataGranularity, FillReport, MarketRecord, OrderIntent, PortfolioSnapshot, ServiceHealth, Signal
class MarketDataProvider(Protocol):
    provider_name: str
    def historical(self, *, symbol: str, start: datetime, end: datetime, granularity: DataGranularity, include_extended_hours: bool) -> Sequence[MarketRecord]: ...
    def latest(self, *, symbol: str, granularity: DataGranularity) -> Sequence[MarketRecord]: ...
    def health(self) -> ServiceHealth: ...
class Strategy(Protocol):
    name: str; version: str
    def generate_signals(self, *, market_records: Sequence[MarketRecord], portfolio: PortfolioSnapshot) -> Sequence[Signal]: ...
class BrokerAdapter(Protocol):
    adapter_name: str
    def connect(self) -> ServiceHealth: ...
    def health(self) -> ServiceHealth: ...
    def submit_order(self, intent: OrderIntent): ...
    def cancel_order(self, broker_order_id: str, *, reason: str): ...
    def list_open_orders(self) -> Sequence[object]: ...
    def fills(self) -> Sequence[FillReport]: ...
